/**
 * Autogenerated by Thrift Compiler (0.9.2)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.apache.thrift.struct.java.dep.vo;
public enum StudentEnum implements org.apache.thrift.TEnum {
  ONE(0), TWO(1), THREE(10), REPLY(11);
  private final int value;
  private StudentEnum(int value) {
    this.value = value;
  }
  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   *
   * @return null if the value is not found.
   */
  public static StudentEnum findByValue(int value) {
    switch (value) {
      case 0:
        return ONE;
      case 1:
        return TWO;
      case 10:
        return THREE;
      case 11:
        return REPLY;
      default:
        return null;
    }
  }
  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }
}
